[package]
name = "spacenav"
version = "0.0.1"
authors = []
edition = "2021"

[lib]
name = "spacenav"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
spacenav-plus = "0.1.1"
